#pragma config(Sensor, S1,     HTAC,           sensorI2CCustom)
#pragma config(Sensor, S2,     RCX1,           sensorReflection)
#pragma config(Sensor, S3,     RCX2,           sensorReflection)
#pragma config(Motor,  motorA,          mA,            tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          mB,            tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorC,          mC,            tmotorNXT, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "hitechnic-accelerometer.h"

int motA, motB, motC;
int light1, light2;
int v = -40, u;
int waiting = 0; //waiting for BT connection

void left()
{
	nMotorEncoder[mB] = 0;
	nMotorEncoder[mC] = 0;
	while(nMotorEncoder[mB] < 650){
		motor[mB] = 50;
		motor[mC] = -50;
		wait1Msec(1);
	}
}

void right()
{
	nMotorEncoder[mB] = 0;
	nMotorEncoder[mC] = 0;
	while(nMotorEncoder[mC] < 650){
		motor[mB] = -50;
		motor[mC] = 50;
		wait1Msec(1);
	}
}

task line()
{
	float k  = 12.0;
	while(true){
		light1 = SensorValue[RCX1];
		light2 = SensorValue[RCX2];
		u = k*(light2 - light1 + 8);
		motB = v + u;
		motC = v - u;
		if (motB >  100)  motB = 100;
		if (motB < -100) motB = -100;
		if (motC >  100)  motC = 100;
		if (motC < -100) motC = -100;
		motor[mB] = motB;
		motor[mC] = motC;
		wait1Msec(1);
	}
}

task v_speed()
{
	while(true)
	{
		if(nNxtButtonPressed == 1){
			v = v - 10;
			while(nNxtButtonPressed != -1) wait1Msec(1);
		}
		if(nNxtButtonPressed == 2){
			v = v + 10;
			while(nNxtButtonPressed != -1) wait1Msec(1);
		}
		wait1Msec(1);
	}
}

task main()
{
	StartTask(v_speed);
	btConnect(2, "CNIIRTK");
	int x_axis = 0, y_axis = 0, z_axis = 0;
	while(true)
	{
		//------------------------------------------------------------------------------------------------------
		//input
		motA = messageParm[0];
		motB = messageParm[1];
		motC = messageParm[2];
		if(cCmdMessageGetSize(mailbox1) != 0)
		{
			waiting = 0;
			if(motB <= 100){
				StopTask(line);
				motor[mB] = motB;
				motor[mC] = motC;
			}
			else
			{
				switch(motB){
				case 101:
					StartTask(line);
					break;
				case 102:
					left();
					break;
				case 103:
					right();
					break;
				}
			}
			motor[mA] = motA;
			ClearMessage();
		}
		else
		{
			waiting++;
			nxtDisplayTextLine(0,"%d", waiting);
			if(waiting < 60)
			{
				PlaySound(soundBlip);
				motor[mA] = motA;
				motor[mB] = motB;
				motor[mC] = motC;
			}
			else
			{
				motor[mA] = 0;
				motor[mB] = 0;
				motor[mC] = 0;
			}
		}
		//------------------------------------------------------------------------------------------------------
		//output
		HTACreadAllAxes(HTAC, x_axis, y_axis, z_axis);
		light1=SensorValue[RCX1];
		light2=SensorValue[RCX2];
		nxtDisplayCenteredBigTextLine(3, "%d", v);
		sendMessageWithParm(light1, light2, z_axis);
		wait1Msec(30);
	}
}
