#pragma config(Sensor, S1,     Up,             sensorTouch)
#pragma config(Sensor, S2,     Down,           sensorTouch)
#pragma config(Sensor, S3,     Stop,           sensorTouch)
#pragma config(Motor,  motorB,          trn,           tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorC,          frd,           tmotorNXT, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//int accel;//+light, sonar

task main()
{
	int n = 1;
	int button;
	int forward, turn;
	int v, u, grey = 23;
	int y_axis, z_axis, x_axis, light1, light2;
	int motA, motB, motC;
	bool operationLine = false;
	int operationTurn = 10;
	float k = 15.0;
	nMotorEncoder[trn] = 0;
	nMotorEncoder[frd] = 0;
	wait1Msec(500);
	while(true)
	{

		//------------------------------------------------------------------------------------------------------
		//main motors
		forward = nMotorEncoder[frd];
		if (forward >= 80) forward = 100;
		if (forward <= -80) forward = -100;
		if (abs(forward) < 10) forward = 0;

		turn = nMotorEncoder[trn];
		if (abs(turn) < 10)
		{
			turn = 0;
		}
		else
		{
			if (turn > 0)
				turn = turn - 10;
			else
				turn = turn + 10;
		}
		if (turn >= 100) turn = 100;
		if (turn <=-100) turn = -100;
		v = forward;
		u = 2*turn;
		//------------------------------------------------------------------------------------------------------
		//manipulator
		motA = 0;
		if (SensorValue[Up] == 1)
			motA = 40;
		if (SensorValue[Down] == 1)
			motA = -40;
		//------------------------------------------------------------------------------------------------------
		//stop button and slow mode
		if (SensorValue[Stop] == 1){
			PlaySound(soundBlip);
			v = 0;
			u = 0;
			if(abs(turn)>15){
				if(turn > 0)
					u = 20;
				else
					u = -20;
			}
			if(abs(forward)>15){
				if(forward > 0)
					v = 10;
				else
					v = -10;
			}
		}
		//------------------------------------------------------------------------------------------------------
		//input
		if(cCmdMessageGetSize(mailbox1) != 0)
		{
			light1 = messageParm[0];
			light2 = messageParm[1];
			z_axis = messageParm[2];
			if(abs(z_axis) > 80) PlaySound(soundUpwardTones);
			ClearMessage();
		}
		//------------------------------------------------------------------------------------------------------
		//screen and buttons
		button = nNxtButtonPressed;
		switch(button){
		case 2:
			n = 2;
			operationTurn = 10;
			while(button != -1){
				button = nNxtButtonPressed;
				wait1Msec(1);
			}
			break;
		case 1:
			n = 3;
			operationTurn = 10;
			while(button != -1){
				button = nNxtButtonPressed;
				wait1Msec(1);
			}
			break;
		case 3:
		  n = 1;
			if (operationLine == true) operationLine = false;
			else operationLine = true;
			while(button != -1){
				button = nNxtButtonPressed;
				wait1Msec(1);
			}
			break;
		}
		//------------------------------------------------------------------------------------------------------
		//final motors
		motB = v + u;
		motC = v - u;
		if (motB >  100)  motB = 100;
		if (motB < -100) motB = -100;
		if (motC >  100)  motC = 100;
		if (motC < -100) motC = -100;
		//------------------------------------------------------------------------------------------------------
		//operation
		if(operationLine == true){
			switch(n){
			case 1:
				motB = 101;
				break;
			}
		}
		if(operationTurn > 0){
			switch(n){
			case 2:
				motB = 102;//left
				break;
			case 3:
				motB = 103;//right
				break;
			}
		}
		//------------------------------------------------------------------------------------------------------
		//output
		nxtDisplayTextLine(1,"enc:%2d  fwd:%3d",nMotorEncoder[frd], forward);
		nxtDisplayTextLine(2,"enc:%3d  trn:%3d",nMotorEncoder[trn], turn);
		nxtDisplayTextLine(3,"v:%3d  u:%3d", v, u);
		nxtDisplayTextLine(4,"mB:%3d  mC:%3d", motB, motC);
		nxtDisplayTextLine(5,"Z:%3d", z_axis);
		nxtDisplayTextLine(6,"L1:%3d  L2:%3d", light1, light2);
		nxtDisplayTextLine(7,"%d",n);
		sendMessageWithParm(motA, motB, motC);
		//------------------------------------------------------------------------------------------------------
		wait1Msec(30);
		operationTurn = operationTurn - 1;
	}
}
