#pragma config(Sensor, S1,     Gyro,           sensorI2CHiTechnicGyro)
#pragma config(Motor,  motorB,          mB,            tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          mC,            tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "hitechnic-gyro.h"

#define WAIT_TIME    8
#define KGYROANGLE   0.487
#define KSPEED       0.024
#define KGYROSPEED   0.153
#define KPOS         0

task main(){

    float time = WAIT_TIME * 0.001;
    float segway_angle = 0;
    float segway_speed;
    float wheel_angle = 0, last_wheel_angle;
    float wheel_speed;
    int u;

    HTGYROstartCal(Gyro);
    time1[T1] = 0;
    time1[T2] = 0;

    nMotorEncoder[mB] = 0;
    nMotorEncoder[mC] = 0;

    while(true)
    {
        segway_speed = HTGYROreadRot(Gyro);
        segway_angle += segway_speed * 0.001 * time1[T1];
        time1[T1]=0;

        last_wheel_angle = wheel_angle;
        wheel_angle = (nMotorEncoder[mB] + nMotorEncoder[mC]) / 2;
        wheel_speed = (wheel_angle - last_wheel_angle) / time;


        u = KGYROANGLE * segway_angle +
            KSPEED * wheel_speed +
            KGYROSPEED * segway_speed +
            KPOS * wheel_angle;

				u = u * 10;
        motor[mB] = u;
        motor[mC] = u;

        nxtDisplayCenteredBigTextLine(2, "%2.0f", segway_speed);
    		nxtDisplayCenteredBigTextLine(4, "%2.0f", segway_angle);
    		nxtDisplayCenteredBigTextLine(6, "%d", time1[T2]);

    		wait1Msec(10);

    		if((time1[T2] > 10000) && (abs(segway_speed) < 2))
    		{
    			time1[T2] = 0;
    			HTGYROstartCal(Gyro);
    		}
    }
}
